### ISSUE TITLE
Implicit Help Override

### ISSUE THREAD

**Issue by ghost** [frisco82/botCommander#6]
I am trying to override the default help information generation. I have tried creating a custom 'help' command as the first command (as per the docs), but the default help is still displayed.

I am not sure what additional information to provide. I have a bunch of commands.... they are all working. I create a command named 'help' as the first command, I still see the default help. I must not be understanding the documentation correctly.

**Comment by friscoMad** [comment]
Yes you are right, help was an issue during development as there are several levels, -h options, error on help and it seems that what is documented worked for some time but in the current version is not working anymore and I hadn't a test for that.
Please if possible test with the code in the PR (it is a minor change in lines 1014-1022) I think that's enough but I don't want to release a version without being sure it works with your use case.

**Comment by ghost** [comment]
I really appreciate the quick response on this issue. This project is really helping me out on building a Discord bot for a small project I am working on. I have found all the Discord bot frameworks have terrible command parsing capabilities, and this project ended up being easier to work with for building a Discord bot, than the Discord specific ones. Nice job :)

I tested your fix with both a custom *top level* help command, and a nested sub-command, and my custom help command handler was now invoked for both scenarios.

👍

**Comment by friscoMad** [comment]
This project is like my little child so I am happy to help.
I created it also because I couldn't find anything good enough that was not specific for one platform while I was trying to create a Skype bot. It ended with a lot more features than I needed as I tried to support most of what Commander did but it was a nice project to work on for some time.

But it is really nice to see that it is good enough to be used in the wild and it is helping other developers.

BTW: I have just published version 1.1.2 so you can use it directly

**Comment by ghost** [comment]
I really appreciate the quick turnaround on this, and yes, this is a super-helpful project that I am sure more bot developers knew about. I wasted a lot of time on other Discord frameworks before I said to myself *I really wish they could parse commands like commander parses console options. That is when I found your package :) Take care, and thanks again.
